### ISSUE TITLE
cd example && sh build.sh

### ISSUE THREAD

**Issue by yangqun** [MengRao/pollnet#1]
编译不了，出现很多错误
../Socket.h:195:9: 错误：expected nested-name-specifier before ‘TcpConnection’
   using TcpConnection = SocketTcpConnection<RecvBufSize>;
         ^
../Socket.h:195:9: 错误：在类作用域使用非成员的 using 声明
../Socket.h:195:23: 错误：expected ‘;’ before ‘=’ token
   using TcpConnection = SocketTcpConnection<RecvBufSize>;
                       ^
../Socket.h:195:23: 错误：expected unqualified-id before ‘=’ token
../Socket.h:196:9: 错误：expected nested-name-specifier before ‘TcpConnectionPtr’
   using TcpConnectionPtr = std::unique_ptr<TcpConnection>;
         ^
../Socket.h:196:9: 错误：在类作用域使用非成员的 using 声明
../Socket.h:196:26: 错误：expected ‘;’ before ‘=’ token
   using TcpConnectionPtr = std::unique_ptr<TcpConnection>;
                          ^
../Socket.h:196:26: 错误：expected unqualified-id before ‘=’ token
../Socket.h:246:3: 错误：‘TcpConnectionPtr’不是一个类型名
   TcpConnectionPtr accept() {

**Comment by yangqun** [comment]
加一个 -std=c++11就可以了

**Comment by Ultraman95** [comment]
![1589966475(1)](https://user-images.githubusercontent.com/1725360/82429364-58a69f80-9abe-11ea-996d-453c15f0540b.png)
加了 -std=c++11，还是报错
![1589966513(1)](https://user-images.githubusercontent.com/1725360/82429419-6cea9c80-9abe-11ea-86a1-be361b2f8410.png)

**Comment by Ultraman95** [comment]
这是什么原因呢，我的机器安装了solarflare网卡的

**Comment by Ultraman95** [comment]
我用的gcc版本是4.8.5

**Comment by Ultraman95** [comment]
set -e

SOLARFLARE_OPT="-DUSE_SOLARFLARE -lonload_zf_static -lciul1"
#SOLARFLARE_OPT=""

g++  -std=c++11  -O3 tcpclient.cc -o tcpclient $SOLARFLARE_OPT

**Comment by Ultraman95** [comment]
[root@localhost example]# ./build.sh
In file included from tcpclient.cc:4:0:
../Tcpdirect.h: In constructor ‘TcpdirectTcpConnection<4096u>::TcpdirectTcpConnection()’:
../Tcpdirect.h:48:7: error: incompatible types in assignment of ‘const char [1]’ to ‘char [64]’
 class TcpdirectTcpConnection
       ^
../Tcpdirect.h: In constructor ‘TcpdirectTcpClient<>::TcpdirectTcpClient()’:
../Tcpdirect.h:212:7: note: synthesized method ‘TcpdirectTcpConnection<4096u>::TcpdirectTcpConnection()’ first required here 
 class TcpdirectTcpClient : public TcpdirectTcpConnection<RecvBufSize>
       ^
tcpclient.cc: In function ‘int main(int, char**)’:
tcpclient.cc:43:13: note: synthesized method ‘TcpdirectTcpClient<>::TcpdirectTcpClient()’ first required here 
   TcpClient client;
             ^

**Comment by Ultraman95** [comment]
tcpclient,tcpserver都编译不过，其他两个可以编译通过

**Comment by MengRao** [comment]
我没有gcc4.8.5可以测试，不过从编译错误来看可能和这句代码有关：
`char last_error_[64] = "";`
你试试改成`char last_error_[64] = {0};`行不行？

**Comment by Ultraman95** [comment]
有一个问题，比如在ip是192.168.92.11的机器上，我这样运行./tcpserver aa 127.0.0.1
我在另外一台机器上运行./tcpclient aa 192.168.92.11收不到数据？./tcpserver aa 127.0.0.1 改成 ./tcpserver aa 192.168.92.11才可以

**Comment by MengRao** [comment]
tcpdirect必须用网卡ip，不支持127.0.0.1或0.0.0.0

**Comment by Ultraman95** [comment]
谢谢
又有一个问题，我在一台没有solarflare的机器上运行./tcpserver aa 192.168.92.11
然后在一台ip为192.168.92.211的有solarflare的机器上运行./tcpsniffer
其中interface为p1p1
src_ip = 192.168.92.11
src_port = 1234
dst_ip = 192.168.92.211
dst_port = 随便填
这样好像收不到数据？是不是我的参数填错了？

**Comment by Ultraman95** [comment]
> tcpdirect必须用网卡ip，不支持127.0.0.1或0.0.0.0

这个是solarflare的规定是吗？

**Comment by MengRao** [comment]
tcpsniffer是抓本机收到的包，你tcpdump能抓到包吗？

**Comment by Ultraman95** [comment]
是不是应该这样
在192.168.92.11上部署./tcpserver aa 192.168.92.11
在192.168.92.212上部署./tcpclient  p1p1 192.168.92.11 ，接受server的包
然后通过
在192.168.92.212上部署./tcpsniffer p1p1 192.168.92.11 1234  192.168.92.212 dst_port 来抓包，是吗？其中dst_port 如何获取？

**Comment by MengRao** [comment]
dst_port填0，就是*，ip填0.0.0.0相当于*

**Comment by Ultraman95** [comment]
不知道，你是否是从事金融的
通过交易所的api，连接到交易所收行情，这样链路就能一直存在，数据包会一直发送过来，然后通过tcpsniffer去抓包，快速解析，是这个套路吗？
