### ISSUE TITLE
请问接收UDP数据, FPGA能比solarflare的efvi模式快多少?

### ISSUE THREAD

**Issue by ghost** [MengRao/pollnet#10]
大佬用过FPGA接收行情吗? 比较好奇. 谢谢.

**Comment by MengRao** [comment]
理论上1us左右

**Comment by ghost** [comment]
我看知乎上有大佬说, efvi的1/2 RTT总共也才750ns啊, 怎么能快1us那么多呢? 时间是从哪到哪计算的?
https://zhuanlan.zhihu.com/p/59242346

**Comment by MengRao** [comment]
1us左右，不是刚好1us
