### ISSUE TITLE
EFVI DMA内存地址获取

### ISSUE THREAD

**Issue by scorpiostudio** [MengRao/pollnet#12]
请教一下，Efvi.h文件中367行的代码 pkt->post_addr = ef_memreg_dma_addr(&memreg, i * PKT_BUF_SIZE) + sizeof(ef_addr);为何要加sizeof(ef_addr)，按C语言应该是pkt->post_addr = ef_memreg_dma_addr(&memreg, i * PKT_BUF_SIZE)；加sizeof(ef_addr)这个offset是为何呢？

**Comment by MengRao** [comment]
为了跳过post_addr变量

**Comment by scorpiostudio** [comment]
> 为了跳过post_addr变量

跳过post_addr变量不应该是这样：pkt->eth = ef_memreg_dma_addr(&memreg, i * PKT_BUF_SIZE) + sizeof(ef_addr);
  struct pkt_buf
  {
    ef_addr post_addr;
    ci_ether_hdr eth;
    ci_ip4_hdr ip4;
    ci_udp_hdr udp;
  };

**Comment by MengRao** [comment]
post_addr的值是eth的地址

**Comment by scorpiostudio** [comment]
> post_addr的值是eth的地址

非常感谢回复，对照了一下OpenOnload源码eflatency.c中代码理解了。
  for( i = 0; i < N_BUFS; ++i ) {
    struct pkt_buf* pb = (void*) ((char*) pkt_mem + i * BUF_SIZE);
    ef_memreg* memreg = i < N_RX_BUFS ? &rx_vi.memreg : &tx_vi_ptr->memreg;
    pb->dma_buf_addr = ef_memreg_dma_addr(memreg, i * BUF_SIZE);
    pb->dma_buf_addr += offsetof(struct pkt_buf, dma_buf);
  }
