### ISSUE TITLE
zf_init: Failed to initialize Control Plane: Can not access a needed shared library

### ISSUE THREAD

**Issue by headshot289** [MengRao/pollnet#14]

**Comment by MengRao** [comment]
你机器有安装onload吗

**Comment by headshot289** [comment]
> 你机器有安装onload吗

有安装的 8.1.1

**Comment by MengRao** [comment]
目前不支持X3522，只能用X2522

**Comment by headshot289** [comment]
> 目前不支持X3522，只能用X2522

可以加我wx吗？知乎私信过去了，我们需要这方面的技术咨询

**Comment by shenzx2025** [comment]
> > 目前不支持X3522，只能用X2522
> 
> 可以加我wx吗？知乎私信过去了，我们需要这方面的技术咨询

解决了么，怎么解决的？我也遇到了
