### ISSUE TITLE
TCP Stream 对于参数为True处理情况

### ISSUE THREAD

**Issue by xinyangcui** [MengRao/pollnet#15]
对于TCP stream 参数为true的情况，segs_[0]不会更新,后续包如何处理？

**Comment by xinyangcui** [comment]
每次处理都是处理segs[0]的数据，第一个包初始化为0，n_segs=1,i=1,j=1插入位置为segs[1],判断处理的函数部分：

    if (segs[0].first == loc && segs[0].second == loc_end) {
      uint32_t remaining = handler(new_data, new_size); // zero copy
      segs[0].first = segs[0].second - remaining;
      if (remaining) {
        uint32_t consumed = new_size - remaining;
        memcpy(recvbuf + segs[0].first, new_data + consumed, remaining);
      }
    }
    else {
      memcpy(recvbuf + loc, new_data, new_size);
      if (i != 0) return false; // no new data for handler
      uint32_t remaining = handler(recvbuf + segs[0].first, segs[0].second - segs[0].first);
      segs[0].first = segs[0].second - remaining;
    }
直接返回false了，没法处理

**Comment by xinyangcui** [comment]
对于新插入的数据，如果不是在首位segs[0],插入以后没办法处理，只会处理0的情况
if (segs[0].first == loc && segs[0].second == loc_end) {
      uint32_t remaining = handler(new_data, new_size); // zero copy
      segs[0].first = segs[0].second - remaining;
      if (remaining) {
        uint32_t consumed = new_size - remaining;
        memcpy(recvbuf + segs[0].first, new_data + consumed, remaining);
      }
    }
    else {
      memcpy(recvbuf + loc, new_data, new_size);
      if (i != 0) return false; // no new data for handler
      uint32_t remaining = handler(recvbuf + segs[0].first, segs[0].second - segs[0].first);
      segs[0].first = segs[0].second - remaining;
    }

**Comment by xinyangcui** [comment]
如果n_segs = MAX_SEG时候，可能发生了丢包，或者重传太久，此刻后续的数据包怎么处理呢  
if (i == j) {                         // insert new seg
      if (n_seg == MAX_SEG) return false; // too many segs
      for (j = n_seg; j > i; j--) {
        segs[j] = segs[j - 1];
      }
      segs[i].first = loc;
      segs[i].second = loc_end;
      n_seg++;
    }
    else { // merge segs
      segs[i].first = std::min(segs[i].first, loc);
      segs[i].second = std::max(segs[j - 1].second, loc_end);
      uint32_t i2 = i + 1;
      if (i2 < j) {
        for (; j < n_seg; i2++, j++) {
          segs[i2] = segs[j];
        }
        n_seg = i2;
      }
    }

**Comment by MengRao** [comment]
参数为True的话如果丢包会一直等重传。如果会发生丢包后不重传的情况，就把这个参数设成false，此时丢包或乱序后没收到的数据会被丢弃，需要用户自行处理。
