### ISSUE TITLE
想问个问题，udp那个例子，可以接受组播udp行情吗

### ISSUE THREAD

**Issue by heber** [MengRao/pollnet#2]
想问个问题，udp那个例子，可以接受组播udp行情吗。谢谢

**Comment by MengRao** [comment]
当然可以



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Heber Shao <notifications@github.com&gt;
发送时间: 2020年4月10日 22:51
收件人: MengRao/pollnet <pollnet@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[MengRao/pollnet] 想问个问题，udp那个例子，可以接受组播udp行情吗 (#2)





 
想问个问题，udp那个例子，可以接受组播udp行情吗。谢谢

**Comment by Ultraman95** [comment]
udpreceiver只能接受udp或者组播是吗？tcpclient发送的，udpreceiver是无法接受的是吗？

**Comment by MengRao** [comment]
是的
