### ISSUE TITLE
TcpStream 我感觉有BUG

### ISSUE THREAD

**Issue by yuzu762** [MengRao/pollnet#6]
第78行
if(diff <0 ){
  loc -=diff;
  new_data -=diff;
  new_size  += diff;
}
是不是又问题，如果数据重传前面 多一部分是不是要改成
if(diff <0 ){
  loc +=diff;
  new_data +=diff;
  new_size  -= diff;
}
代码看 new_data作为指针减了向前也不对呀

**Comment by yuzu762** [comment]
还想问一下 目前tcp_stream会处理tcp回绕这样的场景吗

**Comment by MengRao** [comment]
diff <0表示收到了已处理的数据，可以丢弃了；tcp回绕可以处理的
