### ISSUE TITLE
如何对延时进行调优

### ISSUE THREAD

**Issue by qcmc17** [MengRao/pollnet#7]
测试环境：
4.4.0-131-generic #157-Ubuntu SMP Thu Jul 12 15:51:36 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
Product Name: Solarflare XtremeScale X2522-25G Adapter

Onload 7.1.2.141
Copyright 2019-2021 Xilinx, 2006-2019 Solarflare Communications, 2002-2005 Level 5 Networks
Built: Dec 23 2021 17:59:55 (release)
Build profile header: <ci/internal/transport_config_opt_extra.h>
Kernel module: 7.1.2.141

根据main分支的代码编译，测试efvi_ping的延时，结果如下
![4c99d6c028510eee7219d79c0226645](https://user-images.githubusercontent.com/48583169/178220769-5be53493-a987-40e1-ac8b-3b42899d76f0.png)

结果抖动较大，有什么优化方向可以指点一下吗

**Comment by MengRao** [comment]
核隔离+绑核

**Comment by qcmc17** [comment]
> 核隔离+绑核

测试的时候已经进行了taskset，我再试试核隔离吧
