### ISSUE TITLE
sfc卡的efvi功能发送udp数据丢包

### ISSUE THREAD

**Issue by lijing316** [MengRao/pollnet#8]
调用方式如下,测试多次，只有一次没有丢包，其他的多次测试都丢包并且丢包比较多，

// interface can be empty for Socket version.
bool init(const char* interface, const char* local_ip, uint16_t local_port, const char* dest_ip, uint16_t dest_port);

// send one udp packet with payload
bool write(const char* payload, uint32_t size);

**Comment by MengRao** [comment]
丢包是有可能的。现在efvi ctpio模式使用了比较激进的低延迟发包方式，缺点是如果网口有其他数据正在发送的话会丢包。

**Comment by lijing316** [comment]
好的好的，如果不使用ctpio模式，直接用rc = ef_vi_transmit(&vi, pkt->post_addr, frame_len, buf_index_)发送，能不能避免丢包的现象啊

**Comment by MengRao** [comment]
这样的话其实不如用socket onload快

**Comment by lijing316** [comment]
好的好的，感谢感谢啊

**Comment by MengRao** [comment]
丢包问题可能是最近的一次修改引入，我已经revert了，你可以再试试

**Comment by lijing316** [comment]
好的好的啊，刚刚看到邮件，最近登录邮箱比较少，我后续再试试啊，看到您2020的帖子上面，好像比较推荐tcpdirect，efvi和tcpdirect比较，哪个比较好啊

**Comment by MengRao** [comment]
能用efvi就用efvi。tcpdirect只是基于efvi的一个封装，限制更多，可以被efvi完全替代掉。

**Comment by lijing316** [comment]
好的好的啊

**Comment by lijing316** [comment]
老师好，测试你这边最新的版本，用ef_vi_transmit_ctpio_fallback发UDP包还是丢包

        if (use_ctpio) {
            uint32_t ipsum = ipsum_cache + iplen;
            ipsum += (ipsum >> 16u);
            ip4->ip_check_be16 = ~ipsum & 0xffff;
            ef_vi_transmit_ctpio(&vi, &pkt->eth, frame_len, 40);
            rc = ef_vi_transmit_ctpio_fallback(&vi, pkt->post_addr, frame_len, buf_index_);
        }
        else {
            rc = ef_vi_transmit(&vi, pkt->post_addr, frame_len, buf_index_);
        }

**Comment by MengRao** [comment]
发包频率多快呢，如果接收方来不及处理是会丢包的。另外，使用了ef_vi_transmit_ctpio_fallback后丢包是否有减轻？

**Comment by lijing316** [comment]
用tcpreplay发TCP包，5倍速情况下，程序处理完发udp包，不用efvi ctpio模式，用普通模式，比对接收端收到的udp数据，结果是可以比对上的；
用tcpreplay发TCP包，一倍速情况下，程序处理完发udp包，用efvi ctpio模式，比对接收端收到的udp数据，结果比对不上，存在部分数据缺失；
更改后的版本，比更改之前的版本，丢包要少一些
