### ISSUE TITLE
OnTcpConnectFailed

### ISSUE THREAD

**Issue by JimmyDemo** [MengRao/pollnet#9]
你好，请问一台机器是不是不能同时运行两个进程啊，
（1）在同一机器先运行tcpServer后，再运行tcpClient，Init入参都是本机IP ，运行tcpclient时，会报错
        OnTcpConnectFailed，bind error Address already in use
（2）当在其他机器运行一个server服务后，在本机器运行一个tcpClient后配置（IP01），再运行一个tcpServer（配置IP02），会报错
         bind error Address already in use
有时间请帮忙解答一下疑惑，感谢

**Comment by MengRao** [comment]
你用的是socket版本的吗？

**Comment by JimmyDemo** [comment]
是的，现在使用的是socket版本，刚开始学习想先用socket熟悉一下；
最终是想用Tcpdirect或者 Evfi 方式，所以只有 socket有这个问题吗？

**Comment by MengRao** [comment]
tcpClient不太可能报bind error的错误吧，它都不会调用bind。你会不会起了两个tcp server?

**Comment by JimmyDemo** [comment]
发现原因了，无论是socket还是tcpdirect,Init入参时，最后一个local_port如果输入相同参数就会出现bind error；
默认不入参或者每次写不相同端口，就不会有问题了，感谢您的答复
